<?php

/**
 * @file
 * Module file for NewsFeeder Demo.
 */

/**
 * Implements hook_menu().
 */
function newsfeeder_demo_menu() {
  $items = [];

  $items['newsfeeder-demo/import-feed-sources'] = [
    'title' => 'Import feed sources',
    'description' => 'Description',
    'access callback' => 'user_access',
    'access arguments' => ['administer site'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['newsfeeder_demo_import_feed_sources_form'],
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  ];
  return $items;
}

/**
 * Custom page callback for newsfeeder-demo/import-feed-sources.
 *
 * @see newsfeeder_demo_menu()
 */
function newsfeeder_demo_import_feed_sources_form($form, &$form_state) {
  $form['actions'] = [
    '#type' => 'actions',
  ];

  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Import'),
  ];

  return $form;
}

/**
 * Submit handler for newsfeeder_demo_import_feed_sources_form().
 *
 * @see newsfeeder_demo_import_feed_sources_form()
 */
function newsfeeder_demo_import_feed_sources_form_submit($form, &$form_state) {
  $batch = [
    'title' => t('Importing demo feed sources'),
    'operations' => [],
    'progress_message' => t('Processed @current feed from @total.'),
    'error_message' => t('An error occurred during processing'),
    'finished' => '_newsfeeder_demo_import_feed_sources_batch_finished',
  ];
  // Get the demo feed source from the file and add them to the queue for
  // import.
  if ($res = fopen(drupal_get_path('module', 'newsfeeder_demo') . '/demo_feed_sources.csv', 'r')) {
    while ($line = fgetcsv($res)) {
      $batch['operations'][] = ['_newsfeeder_demo_import_feed_sources_batch_operation', [array_shift($line)]];
    }
    fclose($res);
  }

  batch_set($batch);
}

/**
 * Batch process callback which import a new the feed source from an url.
 *
 * @param string $url
 *   URL of the feed source.
 * @param array $context
 *   Batch context array.
 *
 * @see newsfeeder_demo_import_feed_sources_form_submit()
 */
function _newsfeeder_demo_import_feed_sources_batch_operation($url, array &$context) {
  if (!newsfeeder_hacks_check_if_feed_source_exists_with_url($url)) {
    try {
      // Try to reach the feed source.
      $response = drupal_http_request($url);
      if ($response->code == 200) {
        $values = [
          'type' => 'feed_source',
          'uid' => 0,
          'status' => 1,
          'comment' => 0,
          'promote' => 0,
        ];
        $node = entity_create('node', $values);
        // Set the feed source node's title, if the parsed title looks valid.
        $title = preg_match(NEWSFEEDER_HACKS_TITLE_REGEXP, $response->data, $matches) ? $matches[1] : NULL;
        if (!empty($title) && is_string($title) && strlen($title) <= 100) {
          $node->title = htmlspecialchars_decode($title);
        }
        else {
          $node->title = $url;
          $context['results']['title_error'][] = $url;
        }
        $node->feeds['FeedsHTTPFetcher']['source'] = $url;
        node_save($node);
        if (!$title) {
          watchdog('newsfeeder_demo', 'Feed source title can not be imported! <a href="@url">View</a>', ['@url' => url('node/' . $node->nid)], WATCHDOG_WARNING);
        }
        watchdog('newsfeeder_demo', 'Feed source successfully imported! <a href="@url">View</a>', ['@url' => url('node/' . $node->nid)], WATCHDOG_INFO);
        $context['results']['success'][] = $url;
      }
      // Bad response.
      else {
        $context['results']['failed'][] = $url;
      }
    }
    catch (Exception $e) {
      // Feed source is unreachable on this url.
      watchdog_exception('newsfeeder_demo', $e);
      $context['results']['failed'][] = $url;
    }
  }
}

/**
 * Implements callback_batch_finished().
 *
 * Batch finish callback for feed source import batch.
 *
 * @see newsfeeder_demo_import_feed_sources_form_submit()
 */
function _newsfeeder_demo_import_feed_sources_batch_finished($success, $results, $operations) {
  if ($success) {
    $items = [
      t('imported: @imported', ['@imported' => count($results['success'])]),
      t('failed: @failed', ['@failed' => count($results['failed'])]),
      t('title import failed: @title_import', ['@title_import' => count($results['title_error'])]),
    ];
    drupal_set_message(t('Import process successfully finished! @details'), [
      '@details' => theme('item_list', ['items' => $items]),
    ], 'status');
  }
  drupal_set_message(t('Import process finished with problems. Check the log for more details!'), 'error');
}
