<?php

/**
 * @file
 * Module file for NewsFeeder Demo.
 */

/**
 * Implements hook_menu().
 */
function newsfeeder_demo_menu() {
  $items = [];

  $items['newsfeeder-demo/import-feed-sources'] = [
    'title' => 'Import feed sources',
    'description' => 'Description',
    'access callback' => 'user_access',
    'access arguments' => ['administer site'],
    'page callback' => 'drupal_get_form',
    'page arguments' => ['newsfeeder_demo_import_feed_sources_form'],
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  ];
  return $items;
}

/**
 * Custom page callback for newsfeeder-demo/import-feed-sources.
 *
 * @see newsfeeder_demo_menu()
 */
function newsfeeder_demo_import_feed_sources_form($form, &$form_state) {
  $form['actions'] = [
    '#type' => 'actions',
  ];

  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Import'),
  ];

  return $form;
}

/**
 * Submit handler for newsfeeder_demo_import_feed_sources_form().
 *
 * @see newsfeeder_demo_import_feed_sources_form()
 */
function newsfeeder_demo_import_feed_sources_form_submit($form, &$form_state) {
  $batch = [
    'title' => t('Importing demo feed sources'),
    'operations' => [],
    'progress_message' => t('Processed @current feed source from @total.'),
    'error_message' => t('An error occurred during processing'),
    'finished' => '_newsfeeder_demo_import_feed_sources_batch_finished',
  ];
  // Get the demo feed source from the file and add them to the queue for
  // import.
  if ($res = fopen(drupal_get_path('module', 'newsfeeder_demo') . '/demo_feed_sources.csv', 'r')) {
    while ($line = fgetcsv($res)) {
      $batch['operations'][] = [
        '_newsfeeder_demo_import_feed_sources_batch_operation',
        [array_shift($line)],
      ];
    }
    fclose($res);
  }

  batch_set($batch);
}

/**
 * Batch process callback which import a new the feed source from an url.
 *
 * @param string $url
 *   URL of the feed source.
 * @param array $context
 *   Batch context array.
 *
 * @see newsfeeder_demo_import_feed_sources_form_submit()
 */
function _newsfeeder_demo_import_feed_sources_batch_operation($url, array &$context) {
  if (!newsfeeder_hacks_check_if_feed_source_exists_with_url($url)) {
    try {
      // Try to reach the feed source.
      $response = drupal_http_request($url);
      if ($response->code == 200) {
        $values = [
          'type' => 'feed_source',
          'uid' => 0,
          'status' => 1,
          'comment' => 0,
          'promote' => 0,
        ];
        $node = entity_create('node', $values);
        // Set the feed source node's title, if the parsed title looks valid.
        if ($title = _newsfeeder_demo_get_title_of_feed_source($response->data)) {
          $node->title = $title;
        }
        else {
          $node->title = $url;
          $context['results']['title_error'][] = $url;
        }
        $node->feeds['FeedsHTTPFetcher']['source'] = $url;
        node_save($node);
        if (!$title) {
          watchdog('newsfeeder_demo', 'Feed source title can not be imported! <a href="@url">View</a>', ['@url' => url('node/' . $node->nid)], WATCHDOG_WARNING);
        }
        watchdog('newsfeeder_demo', 'Feed source successfully imported! <a href="@url">View</a>', ['@url' => url('node/' . $node->nid)], WATCHDOG_INFO);
        $context['results']['success'][] = $url;
      }
      // Bad response.
      else {
        $context['results']['failed'][] = $url;
      }
    }
    catch (Exception $e) {
      // Feed source is unreachable on this url.
      watchdog_exception('newsfeeder_demo', $e);
      $context['results']['failed'][] = $url;
    }
  }
}

/**
 * Implements callback_batch_finished().
 *
 * Batch finish callback for feed source import batch.
 *
 * @see newsfeeder_demo_import_feed_sources_form_submit()
 */
function _newsfeeder_demo_import_feed_sources_batch_finished($success, $results, $operations) {
  if ($success) {
    $items = [
      t('imported: @imported', ['@imported' => count($results['success'])]),
      t('failed: @failed', ['@failed' => count($results['failed'])]),
      t('title import failed: @title_import', ['@title_import' => count($results['title_error'])]),
    ];
    drupal_set_message(t('Import process successfully finished! @details', [
      '@details' => theme('item_list', ['items' => $items]),
    ]), 'status');
  }
  else {
    drupal_set_message(t('Import process finished with problems. Check the log for more details!'), 'error');
  }
}

/**
 * Helper function which extracts the title of the feeds source.
 *
 * @param string $body
 *   XML body of the feed source.
 *
 * @return bool|string
 *   The title of the feed source, or FALSE.
 */
function _newsfeeder_demo_get_title_of_feed_source($body) {
  $doc = new DOMDocument();
  $doc->loadXML($body);
  $xml = new DOMXPath($doc);
  // Try to parse the body as a simple RSS feed.
  $items = $xml->evaluate('//rss/channel/title');
  if ($items->length !== 0) {
    return $items->item(0)->nodeValue;
  }
  // Register additional namespaces for RDF feeds.
  $xml->registerNamespace('rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#');
  $xml->registerNamespace('dc', 'http://purl.org/dc/elements/1.1/');
  $xml->registerNamespace('rss', 'http://purl.org/rss/1.0/');
  $items = $xml->evaluate('//rdf:RDF/rss:channel/rss:title');
  if ($items->length !== 0) {
    return $items->item(0)->nodeValue;
  }
  // Register additional namespaces for ATOM feeds.
  $xml->registerNamespace('atom', 'http://www.w3.org/2005/Atom');
  $items = $xml->evaluate('//atom:feed/atom:title');
  if ($items->length !== 0) {
    return $items->item(0)->nodeValue;
  }

  return FALSE;
}
