<?php
/**
 * @file
 * newsfeeder_demo_cts.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function newsfeeder_demo_cts_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function newsfeeder_demo_cts_node_info() {
  $items = array(
    'feed_item' => array(
      'name' => t('Feed item'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'feed_source' => array(
      'name' => t('Feed source'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
